[package]
name = "wikigrep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.8"
hyper = "1.0.0-rc.2"
reqwest = "0.11.14"
reqwest-oauth1 = "0.2.3"
select = "0.6.0"
clap = "4.1.4"
